### ISSUE TITLE
Sensitive Topics指的是什么

### ISSUE THREAD

**Issue by Romaosir** [thu-coai/ShieldLM#1]
感谢开源！！
看了附录B.1提到支持“Sensitive Topics”，指的是什么呢？是否可以理解是中国的政治敏感呢。如国家分裂/反动言论/敏感政治事件...

**Comment by nonstopfor** [comment]
比如政治和宗教相关的一些文本哈

**Comment by Romaosir** [comment]
好的，谢谢。用到的训练/测试数据有开源计划吗

**Comment by nonstopfor** [comment]
在计划中，可能需要过一段时间
