### ISSUE TITLE
具体的训练代码还会公布吗？

### ISSUE THREAD

**Issue by XiaoluJiayou** [thu-coai/ShieldLM#6]
大佬，请问具体训练LLM的代码可以公布吗？最近在研究大语言模型安全可信增强，对您的工作非常感兴趣，想要基于此进一步研究，请问有什么方法可以获取完整的训练代码吗？

**Comment by nonstopfor** [comment]
训练代码就是标准的SFT哈，目前可以参考一些其他的仓库，我们计划将训练代码和数据后面一起公布出来

**Comment by PCIResearch** [comment]
有计划公布时间吗，对这个项目很感兴趣

**Comment by nonstopfor** [comment]
大概6月中下旬哈，最近这段时间比较忙

**Comment by PCIResearch** [comment]
非常期待，能麻烦发一下训练数据和测试数据样例看一下么

**Comment by PCIResearch** [comment]
@nonstopfor 大佬

**Comment by nonstopfor** [comment]
已更新数据和训练代码哈
