### ISSUE TITLE
run infer_shieldlm.sh will generate some wrong

### ISSUE THREAD

**Issue by XiaoluJiayou** [thu-coai/ShieldLM#7]
![image](https://github.com/thu-coai/ShieldLM/assets/94163973/2dea1497-8472-4c7d-b20f-e63bde01c4f5)
It will be longtime Kartun

**Comment by nonstopfor** [comment]
This depends on your gpu performance. If you run the code on A100, each step should cost less than a minute. Also, you can set the `max_new_tokens` to a small value to speed up.
