### ISSUE TITLE
Question about SFT

### ISSUE THREAD

**Issue by yantijin** [thu-coai/ShieldLM#9]
Exciting to read this work.  I'm curious about why SFT for all parameters is chosen in the paper instead of existing PEFT methods like LoRA series.  I would like to know if you have tried and evaluated the effectiveness of these two fine-tuning schemes.

**Comment by nonstopfor** [comment]
I haven't tried LoRA because our resource is sufficient for full-parameters training and usually LoRA would not be better than full SFT.

**Comment by yantijin** [comment]
Thanks for your comment.
